---
- name: Checking distribution 
  fail:
    msg: "{{ ansible_distribution }} is not supported"
  when: ansible_distribution not in os_valid_distributions

- name: Checking version of OS
  fail:
    msg: "{{ ansible_distribution_version}} of {{ ansible_distribution }} is not supported"
  when: ansible_distribution_version|version_compare(os_minimum_versions[ansible_distribution], '<')

# ha_proxy versions esta en map_haproxy_versions
# balance in cfg is valid