---
- name: "Install required packages on RedHat"
  yum:
    pkg: "{{ item }}"
    state: latest
  when: "ansible_os_family == 'RedHat'"
  with_items:
    - unzip
    - gzip
    - "@Development tools"
    - pcre
    - pcre-devel

- name: "Install required packages on Debian"
  apt:
    pkg: "{{ item }}" 
    state: latest
  when: "ansible_os_family == 'Debian'"
  with_items:
    - unzip
    - gzip
    - build-essential
    - libpcre3
    - libpcre3-dev

    